version: '3.1'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root_pass

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DATABASE=${DATABASE_DATDABASE}
      - RAILS_LOG_TO_STDOUT=1
    depends_on:
      - database
